import turtle

mypen = turtle.Turtle()
mypen.speed(5)
mypen.color('black')
mypen.width(3)

# Write title
mypen.penup()
mypen.goto(0, 100)
mypen.write("Chakravhuya", align="center", font=("Arial", 24, "bold"))
mypen.goto(0, 0)
mypen.pendown()

# Generating Chakravhuya
for i in range(0, 85, 5):
    mypen.forward(i)
    mypen.left(90)
    if i == 80:
        mypen.forward(25)
        mypen.right(90)
        mypen.forward(25)
        mypen.right(90)
        mypen.forward(45)
        mypen.right(90)
        for j in range(i, 90, 5):
            mypen.forward(j+45)
            mypen.right(90)
        mypen.forward(112)
        mypen.right(90)
        mypen.forward(50)
        mypen.backward(50)
        mypen.right(90)
        mypen.forward(112)
        mypen.left(90)
        mypen.forward(130)
        mypen.left(90)
        mypen.forward(125)
        mypen.left(90)
        mypen.forward(45)
        mypen.left(90)
        mypen.forward(25)
        mypen.left(90)
        mypen.forward(25)
        mypen.right(90)
        mypen.forward(80)
        mypen.right(90)
        mypen.forward(75)
        mypen.right(90)
        mypen.forward(70)
        mypen.right(90)
        mypen.forward(35)
        mypen.left(90)
        mypen.forward(45)
        mypen.right(90)
        mypen.forward(70)
        mypen.right(90)
        mypen.forward(145)
        mypen.right(90)
        mypen.forward(150)
        mypen.right(90)
        mypen.forward(132)
        mypen.right(90)
        mypen.forward(70)
        mypen.right(90)
        mypen.forward(20)
        mypen.right(90)
        mypen.forward(40)
        mypen.left(90)
        mypen.forward(92)
        mypen.left(90)
        mypen.forward(100)
        mypen.left(90)
        mypen.forward(102)
        mypen.left(90)
        mypen.forward(28)


mypen.hideturtle()
turtle.done()
       

